kind: pipeline
type: docker
name: default

steps:
# - name: test
#   image: busybox
#   commands:
#   - echo $(date -u +"%s")
- name: build
  image: plugins/docker
  settings:
    repo: essems/hello
    dockerfile: Dockerfile
    tags:
    - ${DRONE_BRANCH/\//-}-$(date -u +"%s")-${DRONE_COMMIT_SHA:0:8}